### ISSUE TITLE
physical modeling syth

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/anklang#12]
### Discussed in https://github.com/tim-janik/anklang/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **Reaper10** May 23, 2023</sup>
This is just an idea for anklang is to have an  physical modeling syth after all there isn't an open source  physical modeling syth but there is tools to make one [Faust](https://faust.grame.fr/)

the ui could be like blender  geometry nodes or bitwig grid
![file](https://github.com/tim-janik/anklang/assets/8137561/b77da130-4b6c-4e6b-91cb-6cba5b0f9a2e)
![Bitwig-BWS3-2_Enter-the-Grid](https://github.com/tim-janik/anklang/assets/8137561/f4832bde-83b6-4779-bf36-b9c6cd498a36)
it would be  a moduler syth in module daw
 this would make a great sound design tool</div>

**Comment by tim-janik** [comment]
Beast did implement a modular synth. Our current focus is on clip centric workflows and getting instrument chains to work. I have a few ideas and code snippets on the back burner for a modular synth instrument (or grid synth). But real work on that won't start anytime soon, b/c other things have much higher priority for now.

Have you actually tried a recent version of Anklang yet, maybe ran one of the Nightlies ?

**Comment by Reaper10** [comment]
> Beast did implement a modular synth. Our current focus is on clip centric workflows and getting instrument chains to work. I have a few ideas and code snippets on the back burner for a modular synth instrument (or grid synth). But real work on that won't start anytime soon, b/c other things have much higher priority for now.
> 
> Have you actually tried a recent version of Anklang yet, maybe ran one of the Nightlies ?

unfortunately no i still window 10 I do have [WSL](https://www.bing.com/search?q=windows+subsystem+for+linux&qs=n&form=QBRE&sp=-1&lq=0&pq=windows+subsystem+for+linux&sc=10-27&sk=&cvid=A8036040DE1E4A7895837C192D7B08D2&ghsh=0&ghacc=0&ghpl=) but I did think that would be an  accurate test. I'd love test if I could. The modular synth is just ui idea forgeneral purpose physical modeling using faust

**Comment by tim-janik** [comment]
> unfortunately no i still window 10 I do have WSL but I did think that would be an accurate test. I'd love test if I could. The modular synth is just ui idea forgeneral purpose physical modeling using faust

Please make sure you can run the software if you want to be able to make constructive contributions to the project.
Also, since you already opened a discussion in #11, we don't need issue tracking right now. So I'll close this, further comments and ideas can be made in the discussion thread.

**Comment by swesterfeld** [comment]
> unfortunately no i still window 10

@Reaper10 Maybe you could try installing Ubuntu 22.04 Linux in a VirtualBox, and then run Anklang from there?
