### ISSUE TITLE
Anklang 0.1.0.dev735 fails to start on Fedora 38

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/anklang#13]
I just tried to start the Appimage in VirtualBox, got this error message:
```
[stefan@fedora Downloads]$ cat /etc/fedora-release 
Fedora release 38 (Thirty Eight)
[stefan@fedora Downloads]$ ./anklang-0.1.0.dev735-x64.AppImage 
Gtk-Message: 18:17:05.904: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:17:05.940: Failed to load module "pk-gtk-module"
Gtk-Message: 18:17:05.975: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:17:05.989: Failed to load module "pk-gtk-module"
/tmp/.mount_anklantfx1cS/anklang-0-1/electron/resources/app/../../../lib/AnklangSynthEngine: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
AnklangSynthEngine: exit: 127
AnklangSynthEngine: connection closed
[stefan@fedora Downloads]$ ls -l /lib64/libFLAC*
lrwxrwxrwx. 1 root root     19 19. Jan 01:00 /lib64/libFLAC++.so.10 -> libFLAC++.so.10.0.0
-rwxr-xr-x. 1 root root 119120 19. Jan 01:00 /lib64/libFLAC++.so.10.0.0
lrwxrwxrwx. 1 root root     17 19. Jan 01:00 /lib64/libFLAC.so.12 -> libFLAC.so.12.0.0
-rwxr-xr-x. 1 root root 408608 19. Jan 01:00 /lib64/libFLAC.so.12.0.0
```

**Comment by tim-janik** [comment]
It looks like the appimage build is not including libFLAC.so.8 as part of the appimage...

**Comment by tim-janik** [comment]
Just for the record, here is the excludelist for appimage builds and libFLAC is not on it:
https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist

**Comment by tim-janik** [comment]
> I just tried to start the Appimage in VirtualBox, got this error message:
> 
> /tmp/.mount_anklantfx1cS/anklang-0-1/electron/resources/app/../../../lib/AnklangSynthEngine: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory

Please test again with at least `anklang-0.1.0.dev770-x64.AppImage`, this version has libFLAC and an important rpath fix to also locate bundled libraries.

**Comment by swesterfeld** [comment]
> Please test again with at least `anklang-0.1.0.dev770-x64.AppImage`

Yes, the issue is fixed now.
