### ISSUE TITLE
Shebangs in *.sh files are wrong

### ISSUE THREAD

**Issue by yurivict** [tim-janik/anklang#17]
Instead of ```#!/bin/bash``` they should be ```#!/usr/bin/env bash```, because bash has different paths on different systems.

**Comment by tim-janik** [comment]
> Instead of `#!/bin/bash` they should be `#!/usr/bin/env bash`, because bash has different paths on different systems.

You are right, thanks.
What system are you building on?

**Comment by yurivict** [comment]
> What system are you building on?

FreeBSD 13.2
