### ISSUE TITLE
Freeverb Default Settings

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/anklang#23]
The default settings for Freeverb currently have: no dry signal, some wet signal. However the typical thing to do at the moment is inserting a Freeverb device at the end of a device chain. So probably what we want is to have **100% dry signal** (as to pass the signal through the Freeverb unaltered) and some amount of wet signal.

Note that if we had FX Tracks/Busses the situation would be different. In an FX Bus, you probably want **0% dry signal** and only wet signal. It might be possible to have two sets of defaults here, one if the device is instantiated inside an FX Track and one if it is instantiated in (at the end) of a device chain.

Btw, I think the property should really display % (not a factor).

Also: since this is a mixing between dry and wet, one other UI option would be to simply have mix% to have one single knob that controls how much dry and wet is used.

**Comment by tim-janik** [comment]
Sounds good, care to work this into a PR?
