### ISSUE TITLE
Inserting Reverb after BlepSynth has no effect

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/anklang#24]
If I create a BlepSynth device and insert a FreeVerb device after it, it doesn't sound different (so no reverb is applied). The same occurs if I use a CLAP Reverb plugin such as Dragon Fly. This used to work before.

I'm using 
```
$ misc/version.sh 
0.2.0.nightly2311052133 441cbca2581a3cc6a91606fd2120a60f67c247eb 2023-11-01 17:48:43 +0100
```

**Comment by swesterfeld** [comment]
I did some further debugging on this, and the FreeVerb process function is called (as it should be). However, the order of processing is wrong, so the FreeVerb processing function gets called **before** the BlepSynth.

If I insert plugins in the "wrong" order, that is first insert the FreeVerb and put the BlepSynth after it, then the reverb gets applied.

**Comment by tim-janik** [comment]
Just a guess, could the ordering in combo.cc we wrong? This is where multiple processors are connected as children.
