### ISSUE TITLE
I can't install deb package and I can't use appimage on Debian Stable

### ISSUE THREAD

**Issue by midiaudio** [tim-janik/anklang#3]
I want try this new DAW but the two binaries have problems in Debian 11 (the last stable).

**1.** With `deb` package:

`Dependency is not satisfiable: libboost-system1.71.0` 

On official repositories is the version 1.74.0 (libboost-system1.74.0). I installed but it doesn't work, and I can't install the software.

**2.** With `appimage` I have the next output:

```
tmp/.mount_anklanTWoNHj/usr/bin/anklang: /tmp/.mount_anklanTWoNHj/usr/lib libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
```
I think that packages were made for old version of debian (or maybe ubuntu) and it's time to update they.

**Comment by tim-janik** [comment]
Thanks for the report, I will look into Debian-11 compatibility when building the next release packages.

**Comment by tim-janik** [comment]
The debian package dependencies are now updated and also the electron binary (your tmp/.../usr/bin/anklang).

You can try installing the latest nightly package now:
https://github.com/tim-janik/anklang/releases/download/Nightly/

It successfully installs in a debian:stable (11) docker environment.
