### ISSUE TITLE
LV2: unique device name generation duplicated with CLAP

### ISSUE THREAD

**Issue by swesterfeld** [tim-janik/anklang#34]
For LV2 .ttl storage in the project zip file, we need to generate a unique name - similar to what CLAP needs for storing its state. Currently I copypasted the function - should this be moved to a base class?

https://github.com/swesterfeld/anklang/blob/e70586945ccf9376a78c4f8aa36631bd68c85ef2/ase/lv2device.cc#L2439

**Comment by tim-janik** [comment]
> For LV2 .ttl storage in the project zip file, we need to generate a unique name - similar to what CLAP needs for storing its state. Currently I copypasted the function - should this be moved to a base class?
> 
> https://github.com/swesterfeld/anklang/blob/e70586945ccf9376a78c4f8aa36631bd68c85ef2/ase/lv2device.cc#L2439

Yeah, it is probably best to move this to DeviceImpl.
