### ISSUE TITLE
loop player

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/anklang#39]
I think it would cool if one day  have  a open source loop file format. 
https://faustlibraries.grame.fr/libs/soundfiles/#soloop 

# like:
[Apple loops ](https://www.bing.com/search?q=Apple%20loops%20File%20format&PC=SANSAAND&form=LWS001&ssp=1&cc=US&setlang=en&darkschemeovr=1&safesearch=moderate)
[rex/rex 2 ](https://www.bing.com/search?q=Reason%20Is%20rex%20file%20format&PC=SANSAAND&form=LWS001&ssp=1&cc=US&setlang=en&darkschemeovr=1&safesearch=moderate)
[acid loop](https://www.bing.com/search?q=acid+loop+file+format&qs=ds&form=QBRE) 

what about adding combining .MKA with [Faust soundfilie.lib](https://faustlibraries.grame.fr/libs/soundfiles/) and with [vamp](https://www.vamp-plugins.org/index.html) or https://cvs.savannah.nongnu.org/viewvc/freecycle/freecycle/
workflow 
https://www.youtube.com/watch?v=Yqrz85rPuEo

This could use tool like the old Time Shift Tool into more useful tools
https://drmukul.github.io/Audacity3.0.0_English_Manual/man/time_shift_tool.html
you repurpose the tool for manual moving slice marker. 

down the line you could use a loop player/instrument like[ octo rex play ](https://www.reasonstudios.com/products/octorex/) 
https://www.youtube.com/watch?v=EbhaeBRb7NA&t=3s

For the loop files, the idea is something similar to the tree will end AID e program. Or Code writing program similar to Sublime text Or CudaText Creve you whatever we're every slice. In the loop file shows up a separate entry into the tree. View like a folder in the tree View or a file in the tree.
![68747470733a2f2f636f6465626572672e6f72672f6174746163686d656e74732f62396161306233662d313662342d343434612d623033322d373038303432336465653332](https://github.com/tim-janik/anklang/assets/8137561/26ba1158-a971-457a-ac35-ac0a856749aa)

Adding support for these formats will help other open source DAWs

**Comment by tim-janik** [comment]
We are currently looping the clips during playback, and trunk has just seen the merge of LiquidSFZ, which can handle loops in samples / SFZ files.
Let us know if you have an actual issue with Anklang, e.g. with a screenshot attached so we can see what you are talking about.
